ERROR - 2022-08-24 08:29:02 --> Table 'sdm-pa.auth' doesn't exist in engine
CRITICAL - 2022-08-24 08:29:02 --> Call to a member function getRow() on bool
#0 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_not_unique('admin_hsd1', 'userid', Array, NULL)
#1 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'User id', 'admin_hsd1', Array, Array)
#2 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#3 C:\xampp73\htdocs\appraisal\app\Controllers\auth\Auth.php(46): CodeIgniter\Controller->validate(Array)
#4 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Auth\Auth->loginProcess()
#5 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Auth))
#6 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp73\htdocs\appraisal\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-08-24 08:33:35 --> Table 'sdm-pa.auth' doesn't exist in engine
CRITICAL - 2022-08-24 08:33:35 --> Call to a member function getRow() on bool
#0 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_not_unique('admin_hsd1', 'userid', Array, NULL)
#1 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'User id', 'admin_hsd1', Array, Array)
#2 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#3 C:\xampp73\htdocs\appraisal\app\Controllers\auth\Auth.php(46): CodeIgniter\Controller->validate(Array)
#4 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Auth\Auth->loginProcess()
#5 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Auth))
#6 C:\xampp73\htdocs\appraisal\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp73\htdocs\appraisal\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
